### ISSUE TITLE
formatoptions unset by ftplugin.vim

### ISSUE THREAD

**Issue by hgvhgv** [vim-pandoc/vim-pandoc#237]
Thanks for the great plugin!

I recently noticed that sometimes formatting was working with lists and sometimes not (i.e., the line would break and add a new bullet, rather than just correct indentation, as if the list were a comment).

For some reason, my `formatoptions` are being reset from `tnroq` (as correctly set by **vim-pandoc**) `tcqj` by **runtime/ftplugin.vim** each time the buffer is reloaded. To replicate, I 

1. opened a new file test.md with my nearly blank vimrc (see below): `nvim -u ~/.config/nvim/blank-init.vim test.md`
2. `:verbose set fo?`: "formatoptions=troqn Last set from ~/.local/share/nvim/plugged/vim-pandoc/ftplugin/pandoc.vim"
3. `i Test <esc>` `:w <cr>` `:e <cr>` `:verbose set fo?`: "formatoptions=tcqj Last set from /usr/share/nvim/runtime/ftplugin.vim"

This seems possibly related to #109 but I have no `autocmd`s. Any suggestions?

I'm on neovim 0.1.7. 

My slim vimrc

```
" some basics 
set undofile            " keep an undo file (undo changes after closing)
set ruler               " show the cursor position all the time
set showcmd             " display incomplete commands
set mouse=              " turn off mouse

" Change tabs to four spaces and set textwidth
set tabstop=4 shiftwidth=4 expandtab
set autoindent
set smartindent

" Switch syntax highlighting on
syntax on

" Enable file type detection.
" with plugin and indent
filetype plugin indent on

" Set ; to leader
let mapleader = ";"
let maplocalleader = ";"


" Plugins
" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.local/share/nvim/plugged')

" Pandoc!
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'

" Add plugins to &runtimepath
call plug#end()

" Plug Options

" Pandoc options
let g:pandoc#folding#fold_yaml = 1
let g:pandoc#formatting#mode = 'hA'
let g:pandoc#formatting#textwidth=80
let g:pandoc#formatting#smart_autoformat_on_cursor_moved = 0
```

**Comment by fmoralesc** [comment]
Possibly fixed by #302.

**Comment by hgvhgv** [comment]
This is still happening for me with the same test. Any suggestions? The auto switching of formatting options is one of the coolest parts of the plugin when it works.

**Comment by hgvhgv** [comment]
I figured out, in a roundabout way, what's happening: the b:undo_ftplugin setting is being executed by the vim ftplugin.vim file. It happens when you run any `:edit` command (so on the current buffer or on a numbered buffer, e.g., `:edit 1`, `:edit #` aka `<C-^>`). Because of vim-pandoc's setting for b:undo_ftplugin, this unsets formatoptions as well as equalprg and some other settings.

I'm still not sure exactly where the issue is, but I think it's to do with b:did_ftplugin not being properly set or being unset. This might lie with vim-pandoc or with my plugin manager, vim-plug, or with the interaction between the two.

Possibly relevant issues:
https://github.com/vim-pandoc/vim-pandoc/issues/349
https://github.com/junegunn/vim-plug/issues/25

If you have any tips, I can keep running this down. But I'm a bit stymied with all the moving parts.

**Comment by hgvhgv** [comment]
It seems that there is a conflict between vim-pandoc and vim in setting the filetype. Somehow b:did_ftplugin and did_load_ftplugin are either not properly defined or are undefined at some point. So neovim filetype.vim is running `setf markdown` and then ftplugin.vim is running `exe b:undo_ftplugin`. Because vim-pandoc is called after filetype.vim and `setlocal ft=pandoc` overrides `setf markdown`, the filetype is correctly set and, when a buffer is first loaded, so is equalprg, formatoptions, and everything else in vim-pandoc. But when `:edit` is run again, those get undone while the filetype remains properly set. Going through a debug file hasn't helped me sort this out.

Another possibly pertinent issue: https://github.com/neovim/neovim/issues/11478.

I don't fully understand how and when the various relevant variables are being / should be defined (b:did_ftplugin, did_load_ftplugin, did_load_filetypes) or how to troubleshoot this. The function did_filetype() also seems relevant, in that it has a counter related to editing another file. What's more, this seems like it would affect a number of vim-pandoc users (running `:edit #` seems common, no?) but that doesn't seem to be the case, which makes me think perhaps vim-plug is related (perhaps it alters the order in which pertinent files are called? cf https://github.com/neovim/neovim/issues/7200 https://github.com/neovim/neovim/issues/6869)?

Sorry for my verbosity. Any guidance would be appreciated.

**Comment by Konfekt** [comment]
Since https://github.com/vim-pandoc/vim-pandoc/pull/302/files#diff-42ca9770510de907dc94ec2b6d7a6d6c86018642382e1d4641b4535ccc8b2237R105 sets `b:did_ftplugin` for markdown files (as listed there), it would first be interesting if the issue for  files with extension `.pandoc` is the same as for those with `.markdown`.

**Comment by hgvhgv** [comment]
It's the same regardless of extension.
```
nvim -u pandoc-equalprg-init.vim test.pandoc
:verbose set equalprg?
> equalprg=pandoc -t markdown-shortcut_reference_links-bracketed_spans-raw_attribute --columns=90 --atx-h
eaders --quiet --reference-links
> Last set from ~/.local/share/nvim/plugged/vim-pandoc/autoload/pandoc/formatting.vim line 105
:edit
:verbose set equalprg?
> equalprg=
```

**Comment by hgvhgv** [comment]
I've tried this out with vim proper and with other plugin managers, all of which have the same issue. So I'm pretty sure it's an issue with vim-pandoc and ftdetect. But my playing around with ftdetect hasn't produced anything useful. The fact that this doesn't seem to happen to others leaves me even more stumped.

For the time being, I'm just commenting out the b:undo_ftplugin, as I don't need to switch filetypes often.

**Comment by Konfekt** [comment]
Just an idea: Should `b:did_ftplugin` also be set in https://github.com/vim-pandoc/vim-pandoc/blob/master/ftplugin/pandoc.vim ?
It sets the nonstandard `b:pandoc_loaded`.
See `:help ftplugin-overrule`.

**Comment by Konfekt** [comment]
See `:help DISABLING`:

DISABLING

If you are writing a filetype plugin to be used by many people, they need a
chance to disable loading it.  Put this at the top of the plugin: >

	# Only do this when not done yet for this buffer
	if exists("b:did_ftplugin")
	  finish
	endif
	b:did_ftplugin = 1

This also needs to be used to avoid that the same plugin is executed twice for
the same buffer (happens when using an ":edit" command without arguments).

Now users can disable loading the default plugin completely by making a
filetype plugin with only these lines: >

	vim9script
	b:did_ftplugin = 1

This does require that the filetype plugin directory comes before $VIMRUNTIME
in 'runtimepath'!

If you do want to use the default plugin, but overrule one of the settings,
you can write the different setting in a script: >

	setlocal textwidth=70

Now write this in the "after" directory, so that it gets sourced after the
distributed "vim.vim" ftplugin |after-directory|.  For Unix this would be
"~/.vim/after/ftplugin/vim.vim".  Note that the default plugin will have set
"b:did_ftplugin", it is ignored here.

**Comment by Konfekt** [comment]
The formatoptions are initially set to `1n`

```
" autoload/pandoc/formatting.vim (lines 280-288)
function! pandoc#formatting#UseSoftWraps() abort "{{{1
    " reset settings that might have been changed by UseHardWraps
    setlocal textwidth&
    setlocal formatoptions&
    setlocal formatlistpat&

    " soft wrapping
    setlocal wrap
    setlocal formatoptions=1n
```

then reset by

```vim
" ftplugin/pandoc.vim (lines 59-62)
setlocal formatoptions+=n

let b:undo_ftplugin = 'setlocal formatoptions< formatlistpat< matchpairs<'
                \ . '| unlet! b:match_words'
```

Removing ` formatoptions<` keeps the previously set formatoptions.

Therefore a starting point would be to find out why

```vim
" autoload/pandoc/formatting.vim (line 3)
function! pandoc#formatting#Init() abort "{{{1
```

and 

```vim
" autoload/pandoc/formatting.vim (line 280)
function! pandoc#formatting#UseSoftWraps() abort "{{{1
```

are only called once, but not on reloading `:e` the same file.

This is not how it is meant to be.

@hgvhgv : How come your `&formatoptions` are so different from `1n`?

**Comment by hgvhgv** [comment]
from my specific formatting options `let g:pandoc#formatting#mode = 'hA'`

"formatoptions=tnroq Last set from ~/.local/share/nvim/plugged/vim-pandoc/autoload/pandoc/formatting.vim line 272"

```
" autoload/pandoc/formatting.vim (lines 272)
au InsertLeave <buffer> setlocal formatoptions=tnroq
```

**Comment by Konfekt** [comment]
This pull request should clean up the autoload double check mess.

@hgvhgv and @sh9temp : can you test?

**Comment by Konfekt** [comment]
Something to watch out for could be that just by adding an entry to the list of markdown file extensions, neither pattern

```vim
'#filetypedetect#BufNewFile,BufRead#*.{md,markdown,mdown,mkd,mkdn}'
        autocmd! filetypedetect BufNewFile,BufRead *.{md,markdown,mdown,mkd,mkdn}
```

will apply anymore.

I tried first checking successively for each extension `*.md` ..., but then `autocmd!` had no effect.
