### ISSUE TITLE
Python bool errors for html

### ISSUE THREAD

**Issue by ian-mitchell-001** [vim-pandoc/vim-pandoc#241]
I'm trying to compile a markdown file into an HTML file. But, for whatever reason I get this error:
```
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ian/.vim/pythonx/vim_pandoc/command.py", line 111, in __call_
_
    val = os.path.expanduser(val)
  File "/usr/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'bool' object has no attribute 'startswith'
```
The directory I'm in has no spaces in the directory name. Are there any dependencies I may have missed?

**Comment by fmoralesc** [comment]
What is the `:Pandoc` command invocation you are using? (To create an html, the command without arguments should be enough.)

**Comment by fmoralesc** [comment]
This should be fixed now. Can you confirm, @ian-mitchell-001?

**Comment by ian-mitchell-001** [comment]
@fmoralesc I did a fresh install, and got the same error with different lines:

```Python
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ian/.vim/pythonx/vim_pandoc/command.py", line 114, in __call_
_
    val = os.path.expanduser(val)
  File "/usr/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'bool' object has no attribute 'startswith'
```

Running just `:Pandoc` was successful. But, there is math in my document, (and it just typeset as plaintext). I think there might be a Pandoc flag for math that needs to be turned on by default (I would say to use `--webtex` for math). It looks like the error is due to something with the parsing in the html command within the plugin.

**Comment by fmoralesc** [comment]
OK. So, what is the full `Pandoc` invocation you are using now? What are the flags you are passing?

**Comment by fmoralesc** [comment]
I think I got the problem. Can you check if you have the issue with the code in https://github.com/vim-pandoc/vim-pandoc/tree/py3-refactor

**Comment by fmoralesc** [comment]
This should be fixed in master now.

**Comment by ian-mitchell-001** [comment]
Unfortunately, no, it still didn't fix it. I got the error
```Vim
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ian/.vim/bundle/vim-pandoc-py3-refactor/python3/vim_pandoc/command.py", line 136, in __call__
    self._run_command = " ".join(arglist)
TypeError: sequence item 0: expected str instance, bytes found
```
Which looking at the file mentioned, line 136 had the command
```Python
        self._run_command = " ".join(arglist)
```
Did you forget to put in some sort of argument, or forget to put in an HTML function? Looking around the file there wasn't much for HTML.

**Comment by fmoralesc** [comment]
Can you place
```
print(arglist)
```
right before that line and tell me what is the output of that?

**Comment by ian-mitchell-001** [comment]
I put
```
print(arglist)
```
on line 135, and I seemed to get a slightly different output
```
[b'pandoc', b'', '--to="html"', '--output="annotated_code.html"', '--standalone', '--pdf-engine="b\'xelatex\'"', '"annotated_code.md"']
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ian/.vim/bundle/vim-pandoc-py3-refactor/python3/vim_pandoc/command.py", line 136, in __call__
    self._run_command = " ".join(arglist)
TypeError: sequence item 0: expected str instance, bytes found
```
I mentioned this already, but there is math in the document. So you could use arguments such as `--mathml` for rendering math in html files. Here's a part of the manual that could be used to reference [math to html.](https://pandoc.org/MANUAL.html#math-rendering-in-html)

**Comment by fmoralesc** [comment]
Lines 102-103 contain a call to `ensure_string()`, right? The output you give me indicates that they seem to be either missing or not working as intended. If they don't, update.

You can pass the `--mathml` argument yourself, I don't think we should pass it indiscriminately. You should probably take a look at the template system (see `:help vim-pandoc-command-templates`).

**Comment by ian-mitchell-001** [comment]
It *does not* include `ensure_string()`. So I put it in line 102. I'll tell you how it runs later.

**Comment by fmoralesc** [comment]
It should have it in line 103 as well. The [latest commit](https://github.com/vim-pandoc/vim-pandoc/commit/6ab0e8ed4dd3325d6b304e8f97f2cba80e3269ae) should have those changes, I think your local copy is out of sync with `master`.

**Comment by ian-mitchell-001** [comment]
It ran great in the latest commit! The only thing it could use would be LaTeX support in html. But that shouldn't be too hard for me to put in myself.
